### ISSUE TITLE
Scatter and Rose ring labels look offcenter

### ISSUE THREAD

**Issue by nellyt** [gjr80/weewx-polarwindplot#13]
Spiral and Trail look alright

**Comment by gjr80** [comment]
I agree scatter is off, rose looks OK to me. Perhaps if you could provide an example. This (well scatter) is most likely related to #12.

**Comment by gjr80** [comment]
May be fixed at commit https://github.com/gjr80/weewx-polarwindplot/commit/29886fa5c2bcaf6bf6fa8b873e21ca873301c5f6. Needs futher testing to verify correct positioning of the polar plot disk.

**Comment by nellyt** [comment]
Looks good here with sqaure, portrait and landscape aspect ratio image sizes
Closing
