### ISSUE TITLE
Change while loops to for range loops in this function ?

### ISSUE THREAD

**Issue by nellyt** [gjr80/weewx-polarwindplot#15]
https://github.com/gjr80/weewx-polarwindplot/blob/00234f4739953fa66381c720541e1714ab0c346c/bin/user/polarWindPlot.py#L693

**Comment by gjr80** [comment]
Yep, range would be better

**Comment by nellyt** [comment]
There are quite a few of these while loops that could probably be tidied

**Comment by gjr80** [comment]
While loop in PolarWindPlot.joinCurve() method retained, remaining while loops changed to for..range() loops. Refer commit https://github.com/gjr80/weewx-polarwindplot/commit/21a3689732d0df5830c400bfa461f1e320e8cad4
