### ISSUE TITLE
Marker and Line colour selection based on speed code block is repeated multiple times. Move to common method.

### ISSUE THREAD

**Issue by nellyt** [gjr80/weewx-polarwindplot#25]
https://github.com/gjr80/weewx-polarwindplot/blob/fc8738b446e0d9cd447a7d044309b1b942cbd056/bin/user/polarWindPlot.py#L1402

**Comment by gjr80** [comment]
get_speed_color() method created in PolarWindPlot base class to handle this. PolarWindSpiralPlot.render_plot() method was previously cutover to use this method, commit https://github.com/gjr80/weewx-polarwindplot/commit/21a3689732d0df5830c400bfa461f1e320e8cad4 does the same for PolarWindTrailPlot.render_plot() method.
