### ISSUE TITLE
TestSkin : image_background_image seems to clip the image size to the background size

### ISSUE THREAD

**Issue by nellyt** [gjr80/weewx-polarwindplot#33]
https://github.com/gjr80/weewx-polarwindplot/blob/dbcc48c74341ef6edbb83f2fe8b04457063caa49/skins/PolarWindPlotTestSkin/skin.conf#L95

**Comment by gjr80** [comment]
Probably has always been the case, I am not sure why I provided the ability to use an image file as the background; I seem to think that the generator I based this on had a similar capability. I am not sure what capabilities PIL/Pillow has in this regard.

**Comment by gjr80** [comment]
Have done a bit of work with background image, refer commit 7799dc0ed2d96c405ed3607129dfcbfba6e7067d

Background image will be resized to fit the specified `image_width` and `image_height` values. Can also specify the resample filter used for resizing (not really needed but it was an option in PIL and easy to implement).
