### ISSUE TITLE
polar_rings : unable to set this to other values without breaking things

### ISSUE THREAD

**Issue by nellyt** [gjr80/weewx-polarwindplot#37]
https://github.com/gjr80/weewx-polarwindplot/blob/f26ea789d547d64628cab8399e58f1fdf5afea72/bin/user/polarWindPlot.py#L410

**Comment by gjr80** [comment]
Yep, quite possible, this was added in as a by-product of another issue I think.

**Comment by gjr80** [comment]
Works now, test skin uses values of 4, 5 and 10 correctly. This may have been linked to #28 and fixing the last bits of hard coded (5) ring numbers has fixed this issue as well.
