### ISSUE TITLE
No releases?

### ISSUE THREAD

**Issue by sally-woolrich** [gjr80/weewx-polarwindplot#45]
I can't find any releases to download...

**Comment by gjr80** [comment]
Sadly no, very much the squeaky wheel that gets fixed around here. That being said this wheel has squeaked today so let's see what we can do?

Back in January you raised issue #43, that seemed to result in a few problems being fixed and a functioning generator. Well functioning under python 3 anyway. The last post in #43 was a check under python 2, did you have any luck with that? I have a couple of hours this morning, I will see if I can get a VM running WeeWX under python2 and check operation against python2. Will also check issue #44, if it is what I suspect it will be an easy fix. If I get those two tasks finished I will put together a release.

**Comment by sally-woolrich** [comment]
Hi

Yes it's working fine, but am now using python 3...

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sally-woolrich** [comment]
Morning

I should be able to copy over – I took a complete copy of the weewx installation away with me.  (the weather Pi I use this on is 20-25 minutes drive away).

I think if I:

  *   Copy skins/PolarWindPlot/*
  *   Copy bin/user/PolarWindPlot.py
  *   Edit weewx.conf

That should do the trick.

But it would be very helpful to be able to download it!

Current Pi is the latest – Bulleye, WeeWx  4.8.0, Python 3.9.2.  OK python is not the absolute latest!

**Comment by sally-woolrich** [comment]
Well the idea of copying it over didn’t work, the difference I think is Python 2 vs Python 3:

Jun 14 08:55:52 sgcweather weewx[638] INFO weewx.cheetahgenerator: Generated 1 files for report WindRose in 0.21 seconds
Jun 14 08:55:52 sgcweather weewx[638] ERROR weewx.reportengine: Unable to instantiate generator 'user.polarWindPlot.PolarWindPlotGenerator'
Jun 14 08:55:52 sgcweather weewx[638] ERROR weewx.reportengine:         ****  invalid syntax (polarWindPlot.py, line 261)
Jun 14 08:55:52 sgcweather weewx[638] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jun 14 08:55:52 sgcweather weewx[638] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 180, in run
Jun 14 08:55:52 sgcweather weewx[638] ERROR weewx.reportengine:         ****      obj = weeutil.weeutil.get_object(generator)(
Jun 14 08:55:52 sgcweather weewx[638] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weeutil/weeutil.py", line 1150, in get_object
Jun 14 08:55:52 sgcweather weewx[638] ERROR weewx.reportengine:         ****      mod = __import__(module)
Jun 14 08:55:52 sgcweather weewx[638] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/polarWindPlot.py", line 261
Jun 14 08:55:52 sgcweather weewx[638] ERROR weewx.reportengine:         ****      except IOError, e:
Jun 14 08:55:52 sgcweather weewx[638] ERROR weewx.reportengine:         ****                    ^
Jun 14 08:55:52 sgcweather weewx[638] ERROR weewx.reportengine:         ****  SyntaxError: invalid syntax
Jun 14 08:55:52 sgcweather weewx[638] ERROR weewx.reportengine:         ****  Generator ignored


# Version: 0.1.0                                    Date: ?? ???????ber 2017
#
# Revision History
#   ?? ???????ber 2017  v0.1.0
#       -   initial release

**Comment by gjr80** [comment]
Yes, that is definitely a python2/python3 error. But hang on, you are using `polarWindPlot.py`, that file was [renamed to `polarwindplot.py` back in January](https://github.com/gjr80/weewx-polarwindplot/issues/43#issuecomment-1013858439) when you raised issue #43. You were using `polarwindplot.py` after that change, did you copy the wrong file?

By the way your plan to copy over is just fine, there is nothing special in an extension package, it just automates some of the copying and configuring.

**Comment by sally-woolrich** [comment]
Thanks, I will take a look at what’s on the current box more carefully and copy again.

Thanks for confirming it should work.

**Comment by gjr80** [comment]
Or if you have internet access the following command will download the current `polarwindplot.py` from Github:
```
$ wget https://raw.githubusercontent.com/gjr80/weewx-polarwindplot/master/bin/user/polarwindplot.py
```

Also, don't forget in `skin.conf` you need:
```
# The list of generators that are to be run:
[Generators]
    generator_list = user.polarwindplot.PolarWindPlotGenerator
```
Case matters here.

**Comment by sally-woolrich** [comment]
Thanks, I’ll give that a whirl later today.

**Comment by sally-woolrich** [comment]
OK have downloaded that version and run it, with some slightly odd results for the scatter chart which is the dot4spiral report.   See attached PDF files.  The first chart - period1dayrose - is OK.

**Comment by gjr80** [comment]
Can't see any pdfs, not sure what (if any) files you can attach to an 'issue'. If you can't attach the file just email to me at (gjroderick at gmail dot com).

**Comment by gjr80** [comment]
Conversation taken off-GitHub.

[v0.1.0](https://github.com/gjr80/weewx-polarwindplot/releases) released today.

**Comment by nellyt** [comment]
V0.1.0 release. Well done Gary!
Sorry I last touched this just before moving house and have not been able to get my weather station up since  :(

**Comment by gjr80** [comment]
Yes Neil, I lost touch with this too until Sally prompted me in January. Fortunately when we left it years ago it was in a state where it pretty much ran OK, though I have found myself scratching my head a few times trying to work out what we meant here and there.

Too bad about your station, don't think I could do without mine.
